/*
 * Stamp the build with the commit it was made from.
 *
 * The question this answers is "is the app on my phone the code I pushed?".
 * A PWA makes that genuinely hard to know: the service worker deliberately
 * never skipWaiting, so an installed app can keep running a bundle from three
 * deploys ago while the server has long moved on, and nothing on screen says so.
 *
 * Two artefacts, both gitignored — they are facts about a build, not source:
 *   • src/kernel/build/stamp.generated.ts — compiled INTO the bundle, so it
 *     says which commit the code you are looking at was built from.
 *   • public/version.json — copied to dist and served, so it says which commit
 *     the SERVER is handing out right now.
 * The app fetches the second and compares it with the first. Different → the
 * running app is behind.
 *
 * Runs from predev / prebuild / pretypecheck / postinstall, so it is always
 * there without anyone remembering it.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Git, but never fatal: a build must not fail because of a missing .git. */
function git(args, fallback = '') {
  try {
    return execSync(`git ${args}`, {
      cwd: root,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

// On Vercel the env vars are authoritative (the checkout can be shallow or
// detached); locally git is. Neither is trusted to exist.
const onVercel = !!process.env.VERCEL;
const sha = process.env.VERCEL_GIT_COMMIT_SHA || git('rev-parse HEAD');
const ref =
  process.env.VERCEL_GIT_COMMIT_REF || git('rev-parse --abbrev-ref HEAD');
const subject = (
  process.env.VERCEL_GIT_COMMIT_MESSAGE || git('log -1 --format=%s')
).split('\n')[0];
const committedAt = git('log -1 --format=%cI');

// Uncommitted work means the build matches NO commit — which is the single
// most useful thing to know when you are staring at a phone wondering what it
// is running. Meaningless on Vercel, which always builds a clean checkout.
const dirty = !onVercel && git('status --porcelain').length > 0;

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

const stamp = {
  sha: sha || 'unknown',
  short: sha ? sha.slice(0, 7) : 'unknown',
  ref: ref || 'unknown',
  subject: subject || '',
  committedAt: committedAt || null,
  builtAt: new Date().toISOString(),
  version: pkg.version,
  /** 'production' | 'preview' | 'development' on Vercel, 'local' otherwise. */
  env: process.env.VERCEL_ENV || 'local',
  dirty,
};

const tsPath = resolve(root, 'src/kernel/build/stamp.generated.ts');
mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(
  tsPath,
  `/* GENERATED by scripts/stamp-build.mjs — do not edit, do not commit. */
import type { BuildStamp } from './build-status';

export const BUILD: BuildStamp = ${JSON.stringify(stamp, null, 2)};
`
);

const jsonPath = resolve(root, 'public/version.json');
mkdirSync(dirname(jsonPath), { recursive: true });
writeFileSync(jsonPath, `${JSON.stringify(stamp, null, 2)}\n`);

console.log(
  `stamped ${stamp.short}${stamp.dirty ? '+dirty' : ''} (${stamp.env})`
);
